- name: Configure Line VTY
  ios_config:
    lines:
       - no service pad
       - no ip domain-lookup
       - no ip http server
       - no ip http secure-server
       - no ip source-route
       - no ip finger
       - ip domain name {{ domain_name }}
       - ip ssh time-out {{ sshtimeoutvalue }}
       - ip ssh version {{ sshversion}}
       - service tcp-keepalives-in
       - service tcp-keepalives-out
       - no logging console
       - service password-encryption
