- name: Configure security paraments for Catalyst Switches
  connection: network_cli
  gather_facts: no
  ignore_errors: yes
  hosts: all

  tasks:
    
    - import_tasks: sh_ip_int.yml
    - import_tasks: config.yml

