- name: Configure security parameters for Catalyst switches
  connection: network_cli
  gather_facts: no
  hosts: all
  strategy: free
  ignore_errors: yes

  tasks:

    - name: Load ACL 46,96
      ios_config:
        lines:
           - 10 permit {{ subnet }} {{ wild_mask }}
           - 20 permit {{ subnet_lan_1 }} {{ wild_mask }}
           - 30 permit {{ subnet_lan_2 }} {{ wild_mask }}
           - 40 permit {{ subnet_lan_1 }} {{ wild_mask }}
           - 50 permit {{ subnet_lan_2 }} {{ wild_mask }}
        parents: "{{ item }}"
      with_items:
        -  ip access-list standard 46
        -  ip access-list standard 96




