- name: configure logging source command
  connection: network_cli
  gather_facts: no
  hosts: switch

  tasks:

  - name: Create Switch Backup
    ios_config:
       backup: yes
       backup_options:
         filename: "{{ inventory_hostname }}.cfg"
         dir_path: /Users/harshad/Documents/Playbooks/sw_backup
