[all]
sandbox-iosxe-latest-1.cisco.com

[all:vars]
ansible_become=yes
ansible_become_method=enable
ansible_network_os=cisco.ios.ios
ansible_user=developer
ansible_password=C1sco12345
#ansible_port=8181
ansible_connection=network_cli
